# Logo Url
# Please enter an absolute path to your logo file
# or remove the following line with replacing logo-header.png with your own logo
logo: /images/logo.png

# Header
menu:
  首页: /
  归档: /archives/index.html
  #Categories:
  关于: /about/index.html
  其他: /404.html

# Article list grouped by year
groupByYear: true

# Content
fancybox: true

# Thumbnail
thumbnail: true

# Scroll Loading
scrollLoading: true

# Sidebar
sidebar: left # sidebar's position (left or right)
social_links:
  #twitter:
  #facebook:
  #google-plus:
  #github: https://dailywerk.github.io
  weibo:
  rss:
widgets:
- recent_posts
- category
#- archive
#- tag
- tagcloud
- links

# Links
links:
  Hexo: http://hexo.io

# Don't Use Google APIs if you are in google-blocked areas
use_google_apis: false

# Miscellaneous
favicon: /favicon.png
google_analytics:
fb_admins:
fb_app_id:
baidu_tongji: true